bigcorp/api/urls.py
from django.urls import path, include
from drf_yasg import openapi
from drf_yasg.views import get_schema_view

from . import views

app_name = 'api'

schema_view = get_schema_view(
    openapi.Info(
        title="BigCorp API",
        default_version='v1',
        description="API for BigCorp",
        terms_of_service="https://example.com/terms/",
        contact=openapi.Contact(email="oYp2V@example.com"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
)

urlpatterns = [
    # Products
    path('products/', views.ProductListAPIView.as_view()),
    path('products/<int:pk>/', views.ProductDetailAPIView.as_view()),
    # Reviews
    path('reviews/', views.ReviewCreateAPIView.as_view()),
    # Users
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.jwt')),
    # Documentation
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

bigcorp/bigcorp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django_email_verification import urls as email_urls

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('account/', include('account.urls', namespace='account')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('recommend/', include('recommend.urls', namespace='recommend')),
    path('email/', include(email_urls), name='email-verification'),
    path('api/v1/', include('api.urls', namespace='api')),
    path('', views.index, name='index'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    import debug_toolbar
    import mimetypes
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    mimetypes.add_type("application/javascript", ".js", True)

bigcorp/cart/urls.py
from django.urls import path 
from . import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart_view, name='cart-view'),
    path('add/', views.cart_add, name='add-to-cart'),
    path('delete/', views.cart_delete, name='delete-from-cart'),
    path('update/', views.cart_update, name='update-cart'),
    
]

bigcorp/payment/urls.py
from django.urls import path

from . import views
from .webhooks import stripe_webhook, yookassa_webhook

app_name = 'payment'

urlpatterns = [
    path('shipping/', views.shipping_view, name='shipping'),
    path('checkout/', views.checkout_view, name='checkout'),
    path('complete-order/', views.complete_order_view, name='complete-order'),
    path('payment-success/', views.payment_success_view, name='payment-success'),
    path('payment-fail/', views.payment_fail_view, name='payment-fail'),
    path('stripe-webhook/', stripe_webhook, name='stripe-webhook'),
    path('yookassa-webhook/', yookassa_webhook, name='yookassa-webhook'),
    path('order/<int:order_id>/pdf/', views.admin_order_pdf, name='admin_order_pdf'),
]

bigcorp/cart/views.py
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse

from shop.models import ProductProxy
from .cart import Cart

def cart_view(request):
    cart = Cart(request)
    
    context = {
        'cart': cart
    }
    
    return render(request, 'cart/cart-view.html', context)


def cart_add(request):
    cart = Cart(request)
    
    if request.POST.get('action') == 'post':
        
        product_id = int(request.POST.get('product_id'))
        product_qty = int(request.POST.get('product_qty'))
        
        product = get_object_or_404(ProductProxy, id=product_id)
        
        cart.add(product=product, quantity=product_qty)
        
        cart_qty = cart.__len__()
        
        response = JsonResponse({'qty': cart_qty, 'product': product.name})
        
        return response


def cart_delete(request):
    cart = Cart(request)
    
    if request.POST.get('action') == 'post':
        
        product_id = int(request.POST.get('product_id'))
        
        cart.delete(product=product_id)
        
        cart_qty = cart.__len__()
        
        cart_total = cart.get_total_price()
                
        response = JsonResponse({'qty': cart_qty, 'total': cart_total})
        
        return response


def cart_update(request):
    cart = Cart(request)
    
    if request.POST.get('action') == 'post':
        
        product_id = int(request.POST.get('product_id'))
        product_qty = int(request.POST.get('product_qty'))
        
        cart.update(product=product_id, quantity=product_qty)
        
        cart_qty = cart.__len__()
        
        cart_total = cart.get_total_price()
                
        response = JsonResponse({'qty': cart_qty, 'total': cart_total})
        
        return response

bigcorp/cart/templates/cart/cart-view.html
{% extends "base.html" %}

{% load static %}
{% load mathfilters %}

{% block content %}

<main class="pt-5">
    <div class="container">
        <div class="pb-3 h5">Cart</div>
        <hr>

        {% if cart %}
        {% for item in cart %}
        {% with product=item.product %}

    
        <br>
        <div class="row mb-4 border product-item">
            <div class="col-md-3 col-lg-2 order-md-first">
                <img 
                src="{{ product.full_image_url }}" 
                class="img-fluid" 
                alt="Responsive image"
                width="200px"
                />
            </div>
            <div class="col-md-9 col-lg-10 ps-md-3 ps-lg-10">
                <a href="{{ product.get_absolute_url }}" class="text-decoration-none text-info">
                    <h1 class="h5 pt-2">{{ product.name }}</h1>
                </a>
                <div class="border">
                    <div class="col border-bottom">
                        <div class="row p-3">
                            <div class="col-6">Product</div>
                            <div class="col-6 text-end">
                                {% if product.discount %}
                                    <span class="text-decoration-line-through fw-bold text-secondary me-2">
                                        $ {{product.price|mul:item.qty}} 
                                    </span>
                                    <span class="fw-bold h4">
                                        ${{product.get_discounted_price|mul:item.qty}}
                                    </span>
                                {% else %}
                                    <span class="fw-bold h4">$ {{ product.price|mul:item.qty }}</span>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="row p-3">
                            <div class="col-12">
                                <label for="select">Qty</label>
                                &nbsp;
                                <select id="select{{product.id}}">
                                    <option selected>{{ item.qty }}</option>
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                    <option value="4">4</option>
                                    <option value="5">5</option>
                                </select>
                                <br>
                                <br>
                                <button class="btn btn-primary btn-sm update-button" type="button" data-index="{{ product.id }}">Update</button>
                                &nbsp;
                                <button class="btn btn-danger btn-sm delete-button" type="button" data-index="{{ product.id }}">Delete</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endwith %}
        {% endfor %}
        {% else %}
        <div class="alert alert-info" role="alert">
            Your cart is empty
        </div>
        {% endif %}
        <div class="col-12 text-end">
            <div class="h6 fw-bold">
                Total: $ 
                <div id="total" class="d-inline-flex">
                    {{ cart.get_total_price }}
                </div>
            </div>
            <button type="button" class="btn btn-success btn-md text-dark mt-4">
                <a class="nav-link text-decoration-none" href="{% url 'payment:checkout' %}">
                    Checkout
                </a>
            </button>
        </div>
    </div>
</main>
<script>
    $(document).on('click', '.delete-button', function(e){
        e.preventDefault();

        $.ajax({
            type: 'POST',
            url: "{% url 'cart:delete-from-cart' %}",
            method: 'POST',
            data: {
                product_id: $(this).data('index'),
                csrfmiddlewaretoken: '{{ csrf_token }}',
                action: 'post'
            },
            success: function(response){
                document.getElementById('lblCartCount').textContent = response.qty
                document.getElementById('total').textContent = response.total
                location.reload();
            },
            error: function (xhr, status, error) {
                console.log(error)
            }
        })
    })

    $(document).on('click', '.update-button', function(e){
        e.preventDefault();

        $.ajax({
            type: 'POST',
            url: "{% url 'cart:update-cart' %}",
            method: 'POST',
            data: {
                product_id: $(this).data('index'),
                product_qty: $('#select' + $(this).data('index') + ' option:selected').text(),
                csrfmiddlewaretoken: '{{ csrf_token }}',
                action: 'post'
            },
            success: function(response){
                document.getElementById('lblCartCount').textContent = response.qty
                document.getElementById('total').textContent = response.total
                location.reload();
            },
            error: function (xhr, status, error) {
                console.log(error)
            }
        })
    })
</script>
{% endblock %}