bigcorp/account/urls.py
from django.contrib.auth import views as auth_views
from django.shortcuts import render
from django.urls import path, reverse_lazy

from . import views


app_name = 'account'

urlpatterns = [
    # Registration and Verification

    path('register/', views.register_view, name='register'),
    path('email-verification/',
         lambda request: render(
             request, 'account/email/email-verification.html'),
         name='email-verification',
         ),

    # Login and Logout

    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),

    # Dashboard

    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('profile-management/', views.profile_management_view,
         name='profile-management'),
    path('account-delete/', views.account_delete, name='account-delete'),

    # Password reset

    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='account/password/password_reset.html',
        email_template_name='account/password/password_reset_email.html',
        success_url=reverse_lazy('account:password_reset_done'),
    ),
        name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='account/password/password_reset_done.html'),
        name='password_reset_done'),
    path('password-reset/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='account/password/password_reset_confirm.html',
        success_url=reverse_lazy('account:password_reset_complete'),
    ),
        name='password_reset_confirm'),
    path('password-reset/complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='account/password/password_reset_complete.html'
    ),
        name='password_reset_complete'),
]

bigcorp/api/urls.py
from django.urls import path, include
from drf_yasg import openapi
from drf_yasg.views import get_schema_view

from . import views

app_name = 'api'

schema_view = get_schema_view(
    openapi.Info(
        title="BigCorp API",
        default_version='v1',
        description="API for BigCorp",
        terms_of_service="https://example.com/terms/",
        contact=openapi.Contact(email="oYp2V@example.com"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
)

urlpatterns = [
    # Products
    path('products/', views.ProductListAPIView.as_view()),
    path('products/<int:pk>/', views.ProductDetailAPIView.as_view()),
    # Reviews
    path('reviews/', views.ReviewCreateAPIView.as_view()),
    # Users
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.jwt')),
    # Documentation
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

bigcorp/bigcorp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django_email_verification import urls as email_urls

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('account/', include('account.urls', namespace='account')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('recommend/', include('recommend.urls', namespace='recommend')),
    path('email/', include(email_urls), name='email-verification'),
    path('api/v1/', include('api.urls', namespace='api')),
    path('', views.index, name='index'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    import debug_toolbar
    import mimetypes
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    mimetypes.add_type("application/javascript", ".js", True)

bigcorp/cart/urls.py
from django.urls import path 
from . import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart_view, name='cart-view'),
    path('add/', views.cart_add, name='add-to-cart'),
    path('delete/', views.cart_delete, name='delete-from-cart'),
    path('update/', views.cart_update, name='update-cart'),
    
]

bigcorp/shop/urls.py
from django.urls import path
from . import views


app_name = 'shop'

urlpatterns = [
    # path('', views.products_view, name='products'),
    path('', views.ProductListView.as_view(), name='products'),
    path('search_products/', views.search_products, name='search-products'),
    path('<slug:slug>/', views.product_detail_view, name='product-detail'),
    path('search/<slug:slug>/', views.category_list, name='category-list'),
]

bigcorp/shop/models.py
from decimal import Decimal
from django.db import models
from django.utils.text import slugify
import random
import string
from django.urls import reverse
from django.core.validators import MinValueValidator, MaxValueValidator



class Category(models.Model):
    """
    A model representing a category in the shop.

    Attributes:
        name (CharField): The name of the category.
        parent (ForeignKey): A foreign key to the parent category.
        slug (SlugField): A slug for the category.
        created_at (DateTimeField): The date and time the category was created.
    """

    name = models.CharField("Категория", max_length=100, db_index=True)
    parent = models.ForeignKey(
        'self',
        blank=True,
        null=True,
        related_name='children',
        on_delete=models.CASCADE
    )
    slug = models.SlugField("URL", max_length=255, unique=True, null=False, editable=True)
    created_at = models.DateTimeField("Дата создания", auto_now_add=True)
    
    class Meta:
        unique_together = (['slug', 'parent'])
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        
    def __str__(self):
        """
        Return a string representation of the category with its parent categories.

        The string representation is a concatenation of the category name and its
        parent categories, using ' -> ' as the separator.

        For example, if the category has the name 'Books' and its parent categories
        are 'Department' and 'Store', the string representation will be
        'Store -> Department -> Books'.
        """
        full_path = [self.name]
        k = self.parent
        while k is not None:
            full_path.append(k.name)
            k = k.parent
        return ' -> '.join(full_path[::-1])
    
    @staticmethod
    def _rand_slug():
        """
        Generate a random slug consisting of 3 characters.

        The slug is made up of lowercase letters and digits.

        Returns:
            str: A random string of 3 characters.
        """

        return ''.join(random.choice(string.ascii_lowercase + string.digits) for _ in range(3))
    
    def save(self, *args, **kwargs):
        """
        Save the category.

        If the category does not have a slug, generate one from the category name
        and a random slug. The slug is generated by concatenating the random slug
        with the category name and passing the result to :func:`slugify`.

        The generated slug is then saved as the category's slug, and the category is
        then saved as usual.
        """
        if not self.slug:
            self.slug = slugify(self._rand_slug() + '-pickBetter' + self.name)
        super(Category, self).save(*args, **kwargs)
        
    def get_absolute_url(self):
        return reverse('shop:category-list', args=[self.slug])
    

class Product(models.Model):
    """
    A model representing a product in the shop.

    Attributes:
        category (ForeignKey): A foreign key to the Category model.
        name (CharField): The name of the product.
        brand (CharField): The brand of the product.
        description (TextField): A description of the product.
        slug (SlugField): A unique slug for the product.
        price (DecimalField): The price of the product.
        image (ImageField): An image of the product.
        available (BooleanField): Availability status of the product.
        created_at (DateTimeField): The date and time when the product was created.
        updated_at (DateTimeField): The date and time when the product was last updated.
    """
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')
    name = models.CharField("Название", max_length=100, db_index=True)
    brand = models.CharField("Бренд", max_length=100)
    description = models.TextField("Описание", blank=True)
    slug = models.SlugField("URL", max_length=255, unique=True, null=False, editable=True)
    price = models.DecimalField("Цена", max_digits=10, decimal_places=2, default=99.99)
    image = models.ImageField("Изображение", upload_to='images/products/%Y/%m/%d', blank=True, default='images/products/default.jpg')
    available = models.BooleanField("Наличие", default=True)
    created_at = models.DateTimeField("Дата создания", auto_now_add=True, db_index=True)
    updated_at = models.DateTimeField("Дата обновления", auto_now=True)
    discount = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(100)])
    
    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        ordering = ['-created_at']
        
    def __str__(self):
        """
        Return the string representation of the product.

        The string representation is the name of the product.
        """

        return self.name
    
    def get_absolute_url(self):
        return reverse('shop:product-detail', args=[self.slug])
    
    def get_discounted_price(self):
        discounted_price = self.price * (Decimal(1) - Decimal(self.discount) / Decimal(100))
        return round(discounted_price, 2)
    
    @property
    def full_image_url(self):
        if self.image:
            return self.image.url
        return None
    
    
class ProductManager(models.Manager):
    def get_queryset(self):
        """
        Return a QuerySet of all avaliable products.
        """
        
        return super(ProductManager, self).get_queryset().filter(available=True)
    
class ProductProxy(Product):
    
    objects = ProductManager()
    
    class Meta:
        proxy = True

bigcorp/shop/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.views.generic import ListView
from django.contrib import messages

from .models import Category, ProductProxy


# def products_view(request):
#     """
#     Return a list of all products.

#     This view shows all products, in a grid.
#     """
#     products = ProductProxy.objects.all()
#     return render(request, 'shop/products.html', {'products': products})

class ProductListView(ListView):
    model = ProductProxy
    context_object_name = 'products'
    paginate_by = 15
    
    def get_template_names(self):
        if self.request.htmx:
            return 'shop/components/product_list.html'
        return 'shop/products.html'

def product_detail_view(request, slug):
    product = get_object_or_404(ProductProxy.objects.select_related('category'), slug=slug)
    
    if request.method == 'POST':
        if request.user.is_authenticated:
            if product.reviews.filter(created_by=request.user).exists():
                messages.error(request, 'You have already reviewed this product')
            else:
                rating = request.POST.get('rating', 3)
                content = request.POST.get('content', '')
                if content:
                    product.reviews.create(rating=rating, content=content, created_by=request.user, product=product)
                    return redirect(request.path)
        else:
            messages.error(request, 'You must be logged in to review a product')

    context = {
        'product': product
    }
    
    return render(request, 'shop/product_detail.html', context)
                


def category_list(request, slug):
    """
    Return a list of products for a given category.

    This view shows all products associated with the given category, in a
    grid.
    """
    category = get_object_or_404(Category, slug=slug)
    products = ProductProxy.objects.select_related('category').filter(category=category)
    context = {
        'category': category,
        'products': products,
    }
    return render(request, 'shop/category_list.html', context)

def search_products(request):
    query = request.GET.get('q')
    products = ProductProxy.objects.filter(name__icontains=query).distinct()
    context = {
        'products': products,
    }
    if not query or not products:
        return redirect('shop:products')
    return render(request, 'shop/products.html', context)

bigcorp/shop/templates/shop/category_list.html
{% extends 'base.html' %}

{% block content %}

<main>
    <div class="album py-5">
        <div class="container">
            <div class="pb-3 h5">{{ category.name|capfirst }}</div>

            <hr><br>

            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
                {% for product in products %}
                <div class="col">
                    <div class="card shadow-sm bg-dark">
                        <img src="{{ product.image.url }}" class="img-fluid" alt="Responsive image">
                        <div class="card-body">
                            <p class="card-text text-light">
                                <a class="text-light text-decoration-none fs-4" href="{{product.get_absolute_url}}">{{product.name|capfirst}}</a>
                            </p>
                            <div class="d-flex justify-content-between align-items-center badge bg-success text-wrap" style="width: 6rem;">
                                <h5 class="card-title">$ {{product.price}}</h5>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</main>

{% endblock %}

bigcorp/shop/templates/shop/product_detail.html
{% extends "base.html" %}

{% load static %}

{% block content %}

<div class="container">
    <main class="pt-5">
        <div class="row g-3">
            <div class="col-md-5 col-lg-5 order-md-first">
                <img src="{{ product.full_image_url }}" alt="Product Image" class="img-fluid mx-auto d-block">
            </div>
            <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                <h1 class="fw-bold lh-1 mb-3">{{ product.name|capfirst }}</h1>
                <strong>{{ product.brand }}</strong>
                <hr>
                <br>
                <p>{{ product.description }}</p>
                <div class="border">
                    <div class="col border-bottom">
                        <div class="row p-3">
                            <div class="col-6">Price</div>
                            <div class="col-6 text-end">
                                {% if product.discount %}
                                    <span class="text-decoration-line-through fw-bold text-secondary me-2">
                                        $ {{product.price}} 
                                    </span> 
                                        <span class="badge rounded-pill" style="background-color: rgb(41, 82, 14);">
                                            discount
                                        </span>
                                    <span class="h4 fw-bold">
                                        $ {{product.get_discounted_price}}
                                    </span>
                                {% else %}
                                    <span class="fw-bold h4">$ {{ product.price }}</span>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="row p-3">
                            <div class="col-6">
                                <label for="select">Qty</label>
                                &nbsp;
                                <select id="select">
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                    <option value="4">4</option>
                                    <option value="5">5</option>
                                </select>
                            </div>
                            <div class="col-6 text-end">
                                <button class="btn btn-success" id="add-button" value="{{ product.id }}">Add to cart</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
    <br>
    {% include 'recommend/recommendation.html' %}
</div>

<script>
    $(document).on('click', '#add-button', function(e){
        e.preventDefault();

        $.ajax({
            url: "{% url 'cart:add-to-cart' %}",
            method: 'POST',
            data: {
                product_id: $('#add-button').val(),
                product_qty: $('#select option:selected').text(),
                csrfmiddlewaretoken: '{{ csrf_token }}',
                action: 'post'
            },
            success: function (response) {
                document.getElementById('lblCartCount').textContent = response.qty
                const add_button = document.getElementById('add-button')
                add_button.disabled = true
                add_button.innerText = "Added to cart"
                add_button.className = "btn btn-secondary"
            },
            error: function (xhr, status, error) {
                console.log(error)
            }
        })
    })

</script>

{% endblock %}

bigcorp/shop/templates/shop/products.html
{% extends "base.html" %}

{% block content %}

<!-- Introduction Section -->
{% if not request.user.is_authenticated %}
    <section class="container py-4 text-center">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">Product List</h1>
                <br>
                <p class="lead text-secondary">Below is a list of all the available products.</p>
                <br>
                <a href='{% url "account:register" %}' class="btn btn-success my-2 my-sm-0">Create an account</a>
            </div>
        </div>
    </section>
{% endif %}
<!-- All products section -->

<section class="album py-5">
    <div class="container">
        <div class="pb-3 h5">All products</div>
        <hr>
        <br>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
            {% include "shop/components/product_list.html" %}
        </div>
    </div>
</section>


{% endblock %}